name: my_app
description: "A new Flutter project."

# The following line prevents the package from being accidentally published to
# pub.dev using flutter pub publish. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  bootstrap_icons: ^1.10.3
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/neek.jpeg
    - assets/Let-her-go-by-passenger.jpg
    - assets/songList2.jpg
    - assets/profile.avif
    - assets/Shweta_Mohan.jpg
    - assets/hiphop.jpeg
    - assets/gv.jpeg
    - assets/bieber.svg
    - assets/hiphop.svg
    - assets/shreyaghosal.svg
    - assets/spb.svg
    - assets/playlisticon.svg
    - assets/lets-icons_add-duotone.svg
    - assets/chinnanjiru.svg
    - assets/vaathi.svg
    - assets/maranamass.svg
    - assets/firesong.svg
    - assets/Hayyoda.svg
    - assets/Bujjikutty.svg
    - assets/Ohraaya.svg
    - assets/playgrid1.svg
    - assets/playgrid2.svg
    - assets/playgrid3.svg
    - assets/playgrid4.svg
